import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import MuclesContextProvider from "./context/MuclesContext";
import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${inter.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MuclesContextProvider>
          <Navbar></Navbar>
          <main>
            {children}
          </main>
          <Footer></Footer>
          <ToastContainer />
        </MuclesContextProvider>
      </body>
    </html >
  );
}
